import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home - First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <div>
          {children}
        </div>

        <div>
          <h2 className="text-center text-lg">Next Js Footer</h2>
        </div>
      </body>
    </html>
  );
}
